Started a new branch and committed all of old changes. Added Hello World Response.
googleinterns/step182-2020 pull request #29
Opened 2020-07-08 05:30 UTC by piercedwilson

Hi Lu and Susan,
After reviewing the Git tutorial, I realized where I was misunderstanding, and I thought it would be easier to just begin a new branch with everything   and then do the rest of my changes for week 3, 4 and 5 here. Is that okay?

For this pull request I just added the first response on the index.html, DataServelet.java, and script.js

2020-07-08 17:44 UTC, lupengscu requested changes
Can you add a .gitignore file to exclude auto-generated files in target directory?

2020-07-08 17:44 UTC, lupengscu commented on pierce-portfolio/portfolio/src/main/webapp/resume.html
> +
Add closing tags

2020-07-08 17:44 UTC, lupengscu commented on pierce-portfolio/portfolio/src/main/webapp/script.js
> +      ['tomatoes are my favorite food', 'I ate an apple every day in 2019', 'I am a middle child', 'I am learning to drive right now', 'I went to boarding school for high school', 'I play the saxopho
Consider divide the array into multiple lines

2020-07-09 01:03 UTC, sliang3 approved these changes

2020-07-09 01:03 UTC, sliang3 commented on pierce-portfolio/portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +// Did not remove this because it will be used in week 3
Can you switch this to "TODO(piercedw): Implement in week 3" so it's more obvious that these are action items?

2020-07-09 01:03 UTC, sliang3 commented on pierce-portfolio/portfolio/src/main/webapp/fotos.html
> +        <br><br>
nit: fix spacing

2020-07-09 01:03 UTC, sliang3 commented on pierce-portfolio/portfolio/src/main/webapp/style.css
> +.image-1 {
nit: image-1 isn't very descriptive, maybe we could do .photo or .image-photo?

2020-07-09 01:03 UTC, sliang3 commented on pierce-portfolio/portfolio/src/main/webapp/style.css
> +    width: 600px;
Also looks like there's some extra spaces here.

2020-07-09 01:03 UTC, sliang3 commented on pierce-portfolio/portfolio/src/main/webapp/style.css
> +
nit: Remove extra line

2020-07-10 23:27 UTC, lupengscu approved these changes

2020-07-13 02:53 UTC, merged